from typing import Literal, Optional

class MagGraphError(Exception): ...

class ResolvedConfig:
    @property
    def root_path(self) -> str: ...
    @property
    def config_path(self) -> str: ...
    @property
    def storage_mode(self) -> str: ...
    def open_index(self) -> GraphIndex: ...

class GraphIndex:
    @classmethod
    def open(cls, root_path: str) -> GraphIndex: ...
    @property
    def root_path(self) -> str: ...
    def __len__(self) -> int: ...
    def list_nodes(self) -> list[str]: ...
    def read_node(self, node_id: str) -> Node: ...
    def read_node_async(self, node_id: str) -> Node: ...
    def traverse(
        self,
        from_id: str,
        depth: int = 2,
        order: Literal["bfs", "dfs"] = "bfs",
    ) -> TraversalResult: ...
    def traverse_async(
        self,
        from_id: str,
        depth: int = 2,
        order: Literal["bfs", "dfs"] = "bfs",
    ) -> TraversalResult: ...

class Node:
    @property
    def id(self) -> str: ...
    @property
    def node_type(self) -> str: ...
    @property
    def source(self) -> Optional[str]: ...
    @property
    def links(self) -> list[str]: ...
    @property
    def body(self) -> str: ...
    @property
    def relative_path(self) -> str: ...
    def to_markdown(self) -> str: ...
    def to_dict(self) -> dict[str, object]: ...

class TraversalNode:
    @property
    def id(self) -> str: ...
    @property
    def depth(self) -> int: ...
    @property
    def path(self) -> list[str]: ...

class TraversalResult:
    @property
    def start(self) -> str: ...
    @property
    def max_depth(self) -> int: ...
    @property
    def order(self) -> str: ...
    @property
    def nodes(self) -> list[TraversalNode]: ...
    def to_markdown(self, index: GraphIndex) -> str: ...

def load_config(path: str) -> ResolvedConfig: ...
def open_index(root_path: str) -> GraphIndex: ...
