use std::collections::BTreeSet;
use std::fs;
use std::path::{Path, PathBuf};

use clap::Args;
use maggraph::{GraphIndex, ResolvedConfig, Result};

#[derive(Debug, Args)]
pub struct ScaffoldArgs {
    /// Emit a FastMCP Python server scaffold
    #[arg(long)]
    pub mcp: bool,

    /// Output directory for generated artifacts (default: current directory)
    #[arg(long, default_value = ".")]
    pub output: PathBuf,

    /// Also write SKILL.md into the graph root
    #[arg(long)]
    pub skill: bool,
}

/// Summary of node types and ids for agent-facing scaffolds.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GraphSchemaSummary {
    pub node_count: usize,
    pub node_types: Vec<String>,
    pub node_ids: Vec<String>,
}

impl GraphSchemaSummary {
    pub fn from_index(index: &GraphIndex) -> Self {
        let mut types = BTreeSet::new();
        let mut ids = Vec::new();

        for (id, entry) in index.iter() {
            ids.push(id.to_string());
            types.insert(entry.metadata.node_type.clone());
        }
        ids.sort();

        Self {
            node_count: index.len(),
            node_types: types.into_iter().collect(),
            node_ids: ids,
        }
    }
}

pub fn run(resolved: &ResolvedConfig, args: &ScaffoldArgs) -> Result<()> {
    if !args.mcp && !args.skill {
        return Err(maggraph::MagGraphError::ConfigValidation(
            "scaffold requires at least one of --mcp or --skill".into(),
        ));
    }

    let index = GraphIndex::open(&resolved.root_path)?;
    let schema = GraphSchemaSummary::from_index(&index);

    if args.mcp {
        let mcp_dir = args.output.join("mcp_server");
        write_mcp_scaffold(&mcp_dir, &schema, &resolved.root_path)?;
        tracing::info!(path = %mcp_dir.display(), "wrote MCP server scaffold");
        println!("MCP scaffold: {}", mcp_dir.display());
    }

    if args.skill {
        let skill_path = resolved.root_path.join("SKILL.md");
        write_skill_md(&skill_path, &schema, &resolved.root_path)?;
        tracing::info!(path = %skill_path.display(), "wrote SKILL.md");
        println!("SKILL.md: {}", skill_path.display());
    }

    Ok(())
}

fn io_index_error(message: impl Into<String>) -> maggraph::MagGraphError {
    maggraph::MagGraphError::Index(message.into())
}

fn write_mcp_scaffold(dir: &Path, schema: &GraphSchemaSummary, graph_root: &Path) -> Result<()> {
    fs::create_dir_all(dir)
        .map_err(|e| io_index_error(format!("create {}: {e}", dir.display())))?;

    let types_list = if schema.node_types.is_empty() {
        "_none_".to_string()
    } else {
        schema
            .node_types
            .iter()
            .map(|t| format!("`{t}`"))
            .collect::<Vec<_>>()
            .join(", ")
    };

    let ids_sample = schema
        .node_ids
        .iter()
        .take(10)
        .map(|id| format!("`{id}`"))
        .collect::<Vec<_>>()
        .join(", ");

    let readme = format!(
        r#"# MagGraph MCP Server (scaffold)

Generated by `maggraph scaffold --mcp`. Wire these tools to the MagGraph CLI or Python bindings (Phase 7).

## Graph

- **Root:** `{root}`
- **Nodes:** {node_count}
- **Types:** {types_list}
- **Sample ids:** {ids_sample}

## Setup

```bash
pip install -r requirements.txt
python server.py
```

## Tools

| Tool | Description |
|------|-------------|
| `traverse_graph` | BFS/DFS traversal from a start node id |
| `get_node` | Read a node by id (metadata + body) |
| `list_nodes` | List indexed node ids |

Regenerate when the graph schema changes: `maggraph scaffold --mcp --skill`.
"#,
        root = graph_root.display(),
        node_count = schema.node_count,
        types_list = types_list,
        ids_sample = if ids_sample.is_empty() {
            "_none_".to_string()
        } else {
            ids_sample
        },
    );

    let requirements = r#"fastmcp>=2.0
"#;

    let server_py = format!(
        r##"""MagGraph FastMCP server scaffold — customize and connect to maggraph CLI or Python API."""

from fastmcp import FastMCP

mcp = FastMCP("MagGraph")

GRAPH_ROOT = r"{root}"
NODE_TYPES = {node_types:?}
KNOWN_NODE_IDS = {node_ids:?}


@mcp.tool
def list_nodes() -> list[str]:
    """List node ids in the MagGraph index."""
    return list(KNOWN_NODE_IDS)


@mcp.tool
def get_node(node_id: str) -> str:
    """Read a node by id. Replace with maggraph.read_node when Python bindings are available."""
    # TODO: subprocess or PyO3 — maggraph index read
    if node_id not in KNOWN_NODE_IDS:
        return f"error: node {{node_id!r}} not found"
    return f"Node {{node_id}} (stub). Implement via maggraph Python bindings or CLI."


@mcp.tool
def traverse_graph(from_id: str, depth: int = 2, order: str = "bfs") -> str:
    """Traverse outgoing edges from from_id. Replace with maggraph.traverse or maggraph query."""
    # TODO: maggraph query --from from_id --depth depth --order order
    if from_id not in KNOWN_NODE_IDS:
        return f"error: start node {{from_id!r}} not found"
    lines = [
        "# Traversal (stub)",
        "",
        f"- Start: {{from_id}}",
        f"- Depth: {{depth}}",
        f"- Order: {{order}}",
        "",
        f"Run: maggraph query --from {{from_id}} --depth {{depth}} --order {{order}}",
    ]
    return "\n".join(lines)


if __name__ == "__main__":
    mcp.run()
"##,
        root = graph_root.display(),
        node_types = schema.node_types,
        node_ids = schema.node_ids,
    );

    fs::write(dir.join("README.md"), readme)
        .map_err(|e| io_index_error(format!("write README.md: {e}")))?;
    fs::write(dir.join("requirements.txt"), requirements)
        .map_err(|e| io_index_error(format!("write requirements.txt: {e}")))?;
    fs::write(dir.join("server.py"), server_py)
        .map_err(|e| io_index_error(format!("write server.py: {e}")))?;

    Ok(())
}

fn write_skill_md(path: &Path, schema: &GraphSchemaSummary, graph_root: &Path) -> Result<()> {
    let types_section = if schema.node_types.is_empty() {
        "_No nodes indexed yet._\n".to_string()
    } else {
        schema
            .node_types
            .iter()
            .map(|t| format!("- `{t}`"))
            .collect::<Vec<_>>()
            .join("\n")
            + "\n"
    };

    let ids_section = if schema.node_ids.is_empty() {
        "_No nodes indexed yet._\n".to_string()
    } else {
        schema
            .node_ids
            .iter()
            .map(|id| format!("- `{id}`"))
            .collect::<Vec<_>>()
            .join("\n")
            + "\n"
    };

    let content = format!(
        r#"---
maggraph_skill_version: "0.1.0"
graph_root: "{root}"
node_count: {node_count}
---

# MagGraph Agent Skill

Machine-readable tool manual for this graph instance. Regenerate with `maggraph scaffold --skill`.

## Graph

| Field | Value |
|-------|-------|
| Root | `{root}` |
| Nodes | {node_count} |

## Node types

{types_section}
## Node ids

{ids_section}
## CLI operations

| Command | Purpose |
|---------|---------|
| `maggraph query --from <id> [--depth N] [--order bfs or dfs]` | Traverse graph; Markdown report on stdout |
| `maggraph sync pull` / `push` / `status` | Git sync (when `[sync]` configured) |
| `maggraph scaffold --mcp` | Regenerate FastMCP server under `mcp_server/` |

## MCP

When `mcp_server/` exists, run `python mcp_server/server.py` after `pip install -r mcp_server/requirements.txt`.
Tools: `list_nodes`, `get_node`, `traverse_graph` (stubs until Python bindings land).
"#,
        root = graph_root.display(),
        node_count = schema.node_count,
        types_section = types_section,
        ids_section = ids_section,
    );

    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .map_err(|e| io_index_error(format!("create {}: {e}", parent.display())))?;
    }
    fs::write(path, content)
        .map_err(|e| io_index_error(format!("write {}: {e}", path.display())))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    #[test]
    fn schema_summary_collects_types_and_ids() {
        let root =
            PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../examples/basic/knowledge_graph");
        let index = GraphIndex::open(&root).expect("open");
        let schema = GraphSchemaSummary::from_index(&index);

        assert!(schema.node_count >= 2);
        assert!(schema.node_types.contains(&"note".to_string()));
        assert!(schema.node_ids.contains(&"welcome".to_string()));
    }
}
